# GitHub Pages Settings
theme: minima
markdown: kramdown
highlighter: rouge

# Site Settings
title: Vocab2
description: Learn and master vocabulary with an interactive platform
author: le1tuan
url: https://le1tuan.github.io
baseurl: /vocab2

# Defaults
defaults:
  - scope:
      path: "*.md"
    values:
      layout: page

# Permalink structure
permalink: pretty

# Build settings
lsi: false
excerpt_separator: "\n\n"
incremental: false
plugins:
  - jekyll-feed
  - jekyll-seo-tag
